### PR TITLE
Add line height normal tests for font selection strategy (#245).

### LINKED ISSUE #245: Add line height tests.
Add tests to support w3c/ttml2#1106.

### PR DESCRIPTION
**Pull request by skynavga**
Closes #245.

### CODE REVIEW

**Comment by skynavga** [comment]
> Three things I'm puzzled about with these tests:
> 
> 1. In the absence of line breaks, how can the computed line height be verified?

good point, i'll attempt to address
> 2. all the characters in the test text are vowels with the same acute accent. Is there any reason why the resulting characters might have different heights, or is this expected to be specific to the used font?

the intent here is to have font selection strategy (alone) affect font selection for the purpose of affecting the value of F0, and, therefore, the resulting LH value; keep in mind that LH is computed from the sum of the ascent, descent, and line gap metrics of F0, which need not equal FS;
> 3. setting `tts:fontFamily="default, [anything else]" always results in default, I think, so why bother with the stuff afterwards?

no, this isn't correct, as it will depend upon whether the font selection strategy is auto or character and the default font's character to glyph mapping mapping capabilities

**Comment by nigelmegitt** [comment]
> it will depend upon whether the font selection strategy is auto or character and the default font's character to glyph mapping mapping capabilities

Of course, yes, thanks for that.

**Comment by cconcolato** [comment]
I think I understand the test but because it "requires use of default font that does not support combining character sequences", it might be difficult to demonstrate interop. Is there such a font, available somewhere? Can we create one and add it to the repo?

Also, @nigelmegitt's suggestion in https://github.com/w3c/ttml2-tests/issues/245#issuecomment-594498136 to use `#embedded-font` could be used. Maybe as a separate test if we want to avoid that the testing of this feature depend on `#embedded-font`.

**Comment by skynavga** [comment]
> I think I understand the test but because it "requires use of default font that does not support combining character sequences", it might be difficult to demonstrate interop. Is there such a font, available somewhere? Can we create one and add it to the repo?

I agree that it is not interoperably testable. However, the already existing test for font selection strategy uses the same approach, which we accepted for ttml2 1e. We can take the same approach here, or declare it untestable.

It will be a difficult task to manually construct a font we can include in the time frame we have. This could be done as a future TBD task though.

> 
> Also, @nigelmegitt's suggestion in [#245 (comment)](https://github.com/w3c/ttml2-tests/issues/245#issuecomment-594498136) to use `#embedded-font` could be used. Maybe as a separate test if we want to avoid that the testing of this feature depend on `#embedded-font`.

Use of `#embedded-font` buys nothing here.

**Pull request merged**
