### PR TITLE
Add audio tests.

### LINKED ISSUE #168: Add audio presentation tests.

### PR DESCRIPTION
**Pull request by nigelmegitt**
Audio tests cover the audio style attributes gain, pan, speak and pitch, on span and p elements including audio mixing and animation.

Closes #168.

### CODE REVIEW

**Comment by skynavga** [comment]
@nigelmegitt FYI, I'm in the process of merging this into a new integration branch, issue-0168-audio-presentation-features, for eventual merger to master; so you might want to hold off on further edits until I finish edit and merge; BTW, audio/wav and audio/mp3 are not registered mime types; the registered forms are audio/vnd.wave (RFC2361) and audio/mpeg (RFC3003); also, for completeness, one should specify the codec parameter value, particularly on WAVE resources, since 104 code values are defined (in RFC2361); but since the `AudioFormat` field of the `'fmt '` subchunk maps directly to the codec value, the latter is not really needed; for test resources, we should restrict the audio format (code) value to 1, which is PCM format

**Comment by skynavga** [comment]
@nigelmegitt I ended up changing nearly every file: (1) bad mime media types; (2) animate goes before audio as child of content element; (3) stripped out ID3 structures from mp3 files (leaving only mpeg audio frames); (4) tweaked root element attrs;

**Comment by nigelmegitt** [comment]
Thanks @skynavga for the review and fixes.

I looked for a source for the change of WAV file media type to `audio/vnd.wave`? It seems that `audio/wav` is not registered at IANA but there is a [historic registry](https://www.iana.org/assignments/wave-avi-codec-registry/wave-avi-codec-registry.xml) that does include `audio/vnd.wave`.

**Comment by skynavga** [comment]
@nigelmegitt re: ttva attributes, they are intentionally placed in ALL of the ttml2 test files, both for validation and presentation; this permits interoperation with the TTT (validation and presentation) testing environment, which is (at the moment) our de factor reference implementation; technically, they are permitted and would be pruned by applications that don't recognize them; however, I will place an advisory in the test suite README about this matter; it would be highly detrimental to the testing and IR effort to remove them at this juncture

**Pull request merged**
